#!/bin/bash

USAGE=`cat <<EOF
Usage:
    $0 [-n <N>] [-s <C>,<L>] [-m <M>] <command>

Runs <command> every <N> seconds and plots
the output as a graph in the shell using gnuplot.

The output of <command> must be a list of numbers
separated by whitespaces.

Parameters:
    <N>     :   Seconds between each plot. Default: 10
    <C>,<L> :   Size of the plot in columns and lines. Default: 79,24
    <M>     :   Maximum number of data points to plot. Defaul: 0 = no limit
EOF
`

# Default values
N=10
S=79,24
M=0

# No parameters?
if [ $# -lt 1 ]
then
    echo "Not enough parameters."
    echo
    echo "$USAGE"
    exit 1
fi

# Get options
while getopts "n:s:m:" opt
do
    case $opt in
        n)
            N=$OPTARG
            ;;
        s)
            S=$OPTARG
            ;;
        m)
            M=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            echo
            echo "$USAGE"
            exit 1
            ;;
    esac
done

# Shift away parsed options
shift $((OPTIND-1))
CMD="$@"

echo $CMD

TMPFILE=`mktemp`
trap 'rm $TMPFILE' EXIT

if [ $N -ge 60 ]
then
    PLOTCMD="set term dumb size $S nofeed; set xdata time; set timefmt \"%Y-%m-%d_%H:%M:%S\"; set format x \"%H:%M\"; plot \"$TMPFILE\" using 1:2 with linespoints title \"No1\""
else
    PLOTCMD="set term dumb size $S nofeed; set xdata time; set timefmt \"%Y-%m-%d_%H:%M:%S\"; set format x \"%M:%S\"; plot \"$TMPFILE\" using 1:2 with linespoints title \"No1\""
fi

eval "$CMD" | sed -e "s/^/$(date +%Y-%m-%d_%H:%M:%S) /" >$TMPFILE

COLUMNS=`tail -n 1 $TMPFILE`
i=1

for dump in $COLUMNS
do
    if [ $i -gt 2 ]
    then
        PLOTCMD="$PLOTCMD, \"\" using 1:$i with linespoints title \"No$(( $i - 1 ))\""
    fi
    i=$(( $i + 1 ))
done

gnuplot -e "$PLOTCMD"

while sleep $N
do
    eval "$CMD" | sed -e "s/^/$(date +%Y-%m-%d_%H:%M:%S) /" >> $TMPFILE
    if [[ $M -gt 0 ]]
    then
        TMPTMP=`mktemp`
        tail -n $M $TMPFILE >$TMPTMP
        mv -f $TMPTMP $TMPFILE
    fi
    gnuplot -e "$PLOTCMD"
done
